### ISSUE TITLE
Where can I find the test csv file?

### ISSUE THREAD

**Issue by mingloo** [vinmuk/NFL-predict-yards#1]
Looks like the Kaggle competition provides the `train.csv`? Where can I find the `test.csv` file? 

Or just split the `train.csv` into 2 files?

**Comment by vinmuk** [comment]
Thank you for asking.
Kaggle doesn't provide `test.csv` to prevent leakage, but test API.
So, my actual submit code is slightly different from this code.
Dataset here https://www.kaggle.com/wcukierski/nfl-rush-stage-2-week-1-training-set includes training data, publicLB data and first rerun data, so you can reproduce publicLB and first week rerun by split it.
Thank you.

**Comment by mingloo** [comment]
Thanks for you reply.

But I cannot find the publicLB data and first rerun data in the link: https://www.kaggle.com/wcukierski/nfl-rush-stage-2-week-1-training-set except for a `train.csv` file.

Or is there anything I've misunderstood?

**Comment by vinmuk** [comment]
publicLB data and first rerun data are included in `train.csv`. 2017~ 2018 plays are for training data, 2019 ~2019/10/10 are for publicLB data, and 2019/11/28 ~ are for first week rerun.

**Comment by mingloo** [comment]
Thank you for your prompt support. 

Closed this issue now.
